travis:
  secure:
    BINSTAR_TOKEN: vIZpj96E9JdzHdrV3lvOIRImjQXq1Dyao/W2vETK63mx4+tweEEBnxRG7Hdf59hy+gfPVO4k8GpZef+QrTZep6S0ZVz5GQqJKYUMD9FDchRpYI8yczq6xfuQulUerPI0KAhRZQv5ye2jT4R33bq9W9yG29psUdI/fGw0aSrFE7IUmagRV2pUulMp44lcSAh6Oz3KkmRdsx3CPWshIN/++RPtaWLqn9CD523c5Y7RSGHo7MSTiZSjfm8os/UDQ/RAzB0F8/LHyEIJbdJovcFmbZVIe/h5gY1SynfE+g3W0Zm2kdfQXy7Go91ybf5LDWc8PjjQsDH2SQMrFXKUwlU5hGAxdN/VPQcODjg07iTEU7xTE73yXMiX+sHbVGq53kvcbuPDidyBND5Th2i6zAgBL9lZaGj859hnAoebFEZmFhLSEdJtzJe4JADR1OOpXHvCiM7jwKqPUvHOrNvdQaymcowvio3pP63cH/TZbifC3RCpd7TEU5RMTkkRT6dZuJkhunwn67IRme7JeyLso1m6TVbBU4mJPGKjwrK/SsUlD8YelgNfE1SebIk5mWiqFoXZpk3alez67cET5m3TYWT/1oFcYkfntnCKNbQxgEKXE0/WKqNKQjhrkDxQE+Rb2/zo/r9ZvMYvs9n852sy5nYSp2UK4IfpIiEC1PcfkFekcTo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
